### ISSUE TITLE
Performing HTTP Requests w/ Authorization

### ISSUE THREAD

**Issue by 4lch4** [githubocto/flat#19]
# Overview

I wanted to create a repo that would use the flat action to store some data from the Twitter API. The problem is the Twitter API requires authorization in order to get any data. With the [current version][0] of the flat action (v2.0.2) there's no way to do this.

I created [a fork][1] of this repo that can do just that and published it to [the marketplace][2]. I wanted to submit a PR but wasn't sure if y'all would actually want to add it the way I did it so I figured I'd share what I did and leave it up to y'all.

Below is an explanation of my solution, and here is a link to my repo where I use the action I created:

[4lch4/flat-bot][3]

## My Solution

What I did to enable authorization was add a field to the actions `with` field called `Authorization`. The value of this field is then passed in as an `Authorization` header.

The following code snippets are the changes I made to the existing code, there's only three files I changed (aside from the README):

```typescript http.ts
const response = await axios.get(config.http_url, {
  method: 'get',
  responseType: 'stream',
  headers: {
    Authorization: config.Authorization,
  },
})
```

```typescript config.ts
const HTTPConfigSchema = z
  .object({
    http_url: z.string(),
    Authorization: z.string().optional(),
  })
  .merge(CommonConfigSchema)
// ...
const keys = [
  'downloaded_filename',
  'http_url',
  'Authorization',
  'sql_connstring',
  'sql_queryfile',
  'postprocess',
]
```

```yaml action.yml
Authorization:
  description: 'A string to send as a header for authorizing API requests.'
  required: false
```

## Links

[Current Flat Action Release][0]
[My Fork][1]
[My Published Action][2]
[My Example Usage][3]

[0]: https://github.com/githubocto/flat/releases/tag/v2.0.2
[1]: https://github.com/4lch4/flat
[2]: https://github.com/marketplace/actions/4lch4-flat-data
[3]: https://github.com/4lch4/flat-bot

**Comment by irealva** [comment]
Hi there, thank you for suggesting this and going ahead and trying it out. We love this suggestion. Would you mind starting a PR  for this? 

My one tiny comment would be to use lower cap for the `authorization` key to keep it consistent with the rest.

**Comment by 4lch4** [comment]
Gladly! I'll put a PR together here shortly and submit it :)
