### ISSUE TITLE
Nothing to commit, error code 1

### ISSUE THREAD

**Issue by henryjameslau** [githubocto/flat#25]
I'm trying out using flat to fetch a json file. This json file changes very infrequently so when testing the file is exactly the same. When I try to run the action the commit command gives an error. 

![image](https://user-images.githubusercontent.com/2945099/119522313-c3df1d80-bd73-11eb-80c8-beb59d22563b.png)

[This is my repo where I'm testing things out](https://github.com/henryjameslau/topojson). If anyone has any pointers that'll be great

**Comment by mattrothenberg** [comment]
Hi @henryjameslau, sorry to hear you're having trouble! Your action looks fine to my eyes, and unfortunately I'm unable to reproduce the issue you're running into on my end 😢

Before digging any deeper, are you able to scaffold a new, blank GitHub repository and run the action again? I'd like to know if you're still seeing this error message! Thanks!

**Comment by irealva** [comment]
Also @henryjameslau would you mind [enabling debug output on your repo so we can see more logs](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)? You can do this by:

1. Going to the repo settings > Secrets (from the left side menu) > New repository secrets (Button on the top right)
2. Give it the name `ACTIONS_RUNNER_DEBUG` and value `true`
3. Save the secret
4. Then run the action again and let us know the output.

**Comment by irealva** [comment]
Ok I think it has to do with the `.gitattributes` file. I deleted it and it worked fine for me in a fork of the repo. Can you try deleting it and see if it works for you?

**Comment by henryjameslau** [comment]
@irealva deleting the `.gitattributes` file worked. Thanks for looking into the issue.
