### ISSUE TITLE
Feature Request: Make it possible to hide source

### ISSUE THREAD

**Issue by andmos** [githubocto/flat#37]
👋 
Hi guys, thanks for a cool project! 
I'm using it to sync down some data from a private URL I would like to keep private, so I have configured the URL from a secret like so:

```yaml
http_url: ${{ secrets.MY_SECRET_URL }}
```
But the source comes out in plain text in the commit message:

```json
{
  "date": "2021-05-31T14:01:16.071Z",
  "files": [
    {
      "name": "myfile.json",
      "deltaBytes": 167,
      "source": "https://my_private_server.com"
   }
  ]
}
```
It would be nice to have the repo open, but able to hide the datasource.

**Comment by irealva** [comment]
Hi there, I think the format is just slightly wrong for the param. Can you try: 

`mask: '["${{ secrets.MY_SECRET_URL }}"]'`

Let us know if that works for you.

**Comment by andmos** [comment]
@irealva worked like a charm! Should have checked the docs, with such a new project it was no suprise that this feature was implemented since last I looked. Thanks!
