### ISSUE TITLE
Relative import path "ssf" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by ribtoks** [githubocto/flat#45]
Hi

Thanks for developing flat action.

Yesterday [my action](https://github.com/Xpiks/flat/blob/master/.github/workflows/flat.yml) [started failing](https://github.com/Xpiks/flat/runs/2779429182?check_suite_focus=true) with an error:

```
  Warning Implicitly using latest version (1.0.0) for deno.land/x/url_join/mod.ts
  Error: Error: Command failed: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js data-raw.json
  Warning Implicitly using latest version (1.0.0) for deno.land/x/url_join/mod.ts
  error: Relative import path "ssf" not prefixed with / or ./ or ../ from "cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
  
  error: Relative import path "ssf" not prefixed with / or ./ or ../ from "cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
```

What can I do?

**Comment by jorgeatgu** [comment]
[Same error in my action](https://github.com/jorgeatgu/apaga-luz/runs/2778746671), and in the [bitcoin-demo](https://github.com/githubocto/flat-demo-bitcoin-price/actions).

It looks like it's by Deno update from 1.10.3 to 1.11.0 

[Yesterday](https://github.com/jorgeatgu/apaga-luz/runs/2768572496?check_suite_focus=true): `Going to install stable version 1.10.3.`

[Today](https://github.com/jorgeatgu/apaga-luz/runs/2778746671): `Going to install stable version 1.11.0.`

**Comment by GerryWilko** [comment]
If you specify the Deno version in your setup routine to be `deno-version: v1.10.x` then the action should start working again.

**Comment by Wattenberger** [comment]
Fixed in [the newest release of our postprocessing scripts](https://github.com/githubocto/flat-postprocessing/releases/tag/0.0.11) - it should work if you upgrade to v0.0.11 here:
https://github.com/Xpiks/flat/blob/master/postprocess.js#L5
