### ISSUE TITLE
Error when running githubocto/flat@v2: Relative import path "ssf" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"

### ISSUE THREAD

**Issue by mskyttner** [githubocto/flat#47]
Since three days a step in the github action for the githubcoto/flat@v2 fails with

`Relative import path "ssf" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
`

The log is [here](https://github.com/mskyttner/flat_data_bash_example/runs/2804611455?check_suite_focus=true)

Any hints for how to resolve this issue?

**Comment by nsgrantham** [comment]
In my `postprocess.js` I updated the import statement from `https://deno.land/x/flat@0.0.10/mod.ts` to  `https://deno.land/x/flat@0.0.11/mod.ts` (notice the change from version 0.0.10 to 0.0.11) and that resolved the issue for me.

**Comment by mskyttner** [comment]
Yes, confirming that this took care of the issue! 

Thanks and please feel free to close the issue. 

Or should I do that? Or one of the maintainers?

**Comment by irealva** [comment]
Duplicate issue to #45

**Comment by irealva** [comment]
We fixed this with [https://github.com/githubocto/flat-postprocessing/pull/5](https://github.com/githubocto/flat-postprocessing/pull/5)

Just use the newest version of the Flat postprocessing library: https://deno.land/x/flat@0.0.11/mod.ts
