### ISSUE TITLE
Deno should be run with colored terminal logging output turned off

### ISSUE THREAD

**Issue by grempe** [githubocto/flat#48]
Logging of Deno errors on Github Actions tabs currenty logs Deno output with messy colored terminal output that can't be rendered in the github log tailing UI.

https://share.getcloudapp.com/GGuWQrnk

The `deno` command should be run with color disabled as described in the docs here:

https://deno.land/manual/getting_started/setup_your_environment#environmental-variables

**Comment by irealva** [comment]
Thanks for suggesting this. 

Quick question: so we have the `--allow-env` [flag enabled in our Deno run command](https://github.com/githubocto/flat/blob/main/src/main.ts#L64). Are you not able to create an environment secret on your repo with the variable name `NO_COLOR` and set to `true`? Does this not work?

**Comment by grempe** [comment]
The point is that `deno` should *always* be run without colored terminal output in the context of a Github action.

Not only if the developer pushing action code is aware of how to work around it. So IMHO it should be the default for `flat`
