### ISSUE TITLE
`mod` import should be fixed 

### ISSUE THREAD

**Issue by dalanmiller** [githubocto/flat#52]
Getting an error on my action here: https://github.com/dalanmiller/baby-swim-flat/runs/3052840184?check_suite_focus=true

Looks like the @octokit/request import within `mod.ts` is causing issues with an uncaught error 

```
Error: Command failed: NO_COLOR=true deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.ts classes.json
Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
error: Uncaught (in promise) HttpError: Not Found
      const error = new RequestError(toErrorMessage(data), status, {
                    ^
    at https://cdn.skypack.dev/-/@octokit/request@v5.6.0-rxGSg8zQG4PGwOZo2Cei/dist=es2020,mode=imports/optimized/@octokit/request.js:81:21
    at async file:///home/runner/work/baby-swim-flat/baby-swim-flat/postprocess.ts:348:13
```

**Comment by irealva** [comment]
Hi Dalan,

From the error message it seems like what's actually failing is the `octokit.request` command at line [348](https://github.com/dalanmiller/baby-swim-flat/blob/main/postprocess.ts#L348). Could you verify the postprocess script runs locally on your computer first without any errors? Maybe your configuration for the http request is wrong? You could also wrap the request in a try, catch clause to see if you can log a more specific error message.

You can do this by installing [Deno locally](https://deno.land/manual/getting_started/installation), and running `deno run -q --allow-all --unstable postprocess.ts classes.json`.

**Comment by dalanmiller** [comment]
Thank you @irealva, indeed that was the problem as I didn't read carefully 😅

Deno is really quite amazing, but perhaps the starkest difference it has between a regular node runtime is all the scrutiny done on error handling!
