### ISSUE TITLE
Git push fails with error that remote has changes not available locally

### ISSUE THREAD

**Issue by ribtoks** [githubocto/flat#56]
Hi

Flat action [started to fail](https://github.com/Xpiks/flat/runs/3307010034?check_suite_focus=true) 2 days in a row. The error happens during push

```
! [rejected]        master -> master (fetch first)
  error: failed to push some refs to '<repo>/flat'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I checked and I don't have outdated flat action if it was a known issue.

**Comment by ribtoks** [comment]
Bumping this issue. Flat action still does not work.

**Comment by irealva** [comment]
Hi there,

This can happen sometimes if you edit the repo while the action is running and then the git history becomes corrupted between the one running in the VM for the action and the repo one. 

I created a fork of your code and it works for me: [https://github.com/irealva/flat](https://github.com/irealva/flat).

Could you try:

- deleting data.json manually (you can use the github UI)
- removing this line from your action: [https://github.com/Xpiks/flat/blob/master/.github/workflows/flat.yml#L7](https://github.com/Xpiks/flat/blob/master/.github/workflows/flat.yml#L7)
- running the Flat action manually again?

**Comment by ribtoks** [comment]
Hi @irealva 

Thank you for your time and suggestion. Deleting `data.json` file and rerunning action helped for now.

Before closing the issue, I still would like to better understand what caused the problem. You see, this action was running for a month without interruption and suddenly one day started to fail. There's no way the action was running and meanwhile I `git push`ed something to the repository so the aforementioned error popped up. Do you have any idea what went wrong?

**Comment by irealva** [comment]
That's definitely strange... The only time this has happened to us on our end is when we manually delete or re-add a file or change a file and it triggers the action to run automatically while another action is already running so the git history gets out of sync. In your case where you didn't change anything I can't think of why that would have happened! I'll keep this in mind in case I see the issue again.
