### ISSUE TITLE
Render GeoJSON or Geographic coordinatedata as a map

### ISSUE THREAD

**Issue by gabrielmacedoanac** [githubocto/flat#58]
Could be possible render GeoJSON or geographic coordinate data as a map (eg.: leaflet)?

**Comment by irealva** [comment]
Hi there, just trying to understand is this question related to Flat the action (i.e. how you download the data) or the [Flat Viewer](https://github.com/githubocto/flat-viewer) (i.e. to _view_ the data)?

**Comment by gabrielmacedo** [comment]
Sorry, its about the viewer.

**Comment by gabrielmacedoanac** [comment]
Sorry, its about the viewer.

**Comment by irealva** [comment]
Gotcha, would you mind opening up this issue over there? Will be easier for us to triage and there are a few older issues related to this I think so helpful to keep track of over there.

Thanks!

**Comment by irealva** [comment]
Closing as this has to do with the Flat Viewer, not flat data.
