### ISSUE TITLE
preview failed

### ISSUE THREAD

**Issue by JiangWeixian** [githubocto/flat#61]
![sendpix1](https://user-images.githubusercontent.com/6839576/141642562-1c319888-5e1d-428b-a246-f66976b29958.jpg)

**Comment by irealva** [comment]
Hi there! Would you mind posting this in the [Flat Viewer](https://github.com/githubocto/flat-viewer) repo? That way we can more appropriately triage what's going on. 

Also if you can please share: what is the full link you're using?
