### ISSUE TITLE
[Feature Request] Ability to specify an alternative header name for authorization

### ISSUE THREAD

**Issue by staznz** [githubocto/flat#71]
There is an [authorization](https://github.com/githubocto/flat#authorization-optional) config option which enables the user to specify the `Authorization` HTTP header value. 

However I am wanting to fetch data from an API that uses a **different** header name for authorization. It would be great if we could configure an alternative header name to use for authorization where I could put my secret - `${{secrets.NAME_OF_THE_CREATED_SECRET}}`. 

I am aware of [axios_config](https://github.com/githubocto/flat#axios_config-optional) but I don't believe I can reference secrets in there. Thanks!

**Comment by irealva** [comment]
I actually think [`axios_config`](https://github.com/axios/axios#request-config) might work if you pass in the `headers` property correctly. Could you try it out just to see if it works? If the secret is shown as text I think we can fix that. Something perhaps like:

```
{
  "method": "post",
  "headers": {
    // any custom headers
  }
}
```

There are a few caveats:
* `url` and `baseURL` will both be ignored, use the `http_url` key in Flat
* All function parameters will be ignored (e.g., transformRequest).
* The response type is always set to responseType: 'stream' in the background.

The relevant link of code is [here](https://github.com/githubocto/flat/blob/main/src/backends/http.ts#L25). Just don't pass anything with the `authorization` key and your headers will override the Flat ones.

**Comment by staznz** [comment]
Hi @irealva, I'm aware of the `headers` option in `axios_config`. I would use that but I want to avoid putting a **visible** secret into the json file that it references.

**Comment by staznz** [comment]
It just occurred to me I could create the `axios_config` json file in the workflow!

**Comment by irealva** [comment]
Ah yes sorry that's what I was thinking originally. If the key still shows up in the Action debug workflow let us know! That happened previously with a particular Flat step and we fixed it.
